Feature/keywords
GwentCommunityDevelopers/gwent-data pull request #8
Opened 2017-08-10 14:25 UTC by jamieadkins95

Added a new field `keywords` that lists all of the relevant keywords for a card.

For example Clan Dimun Pirate Captain:

```
"152306": {
    ...
    "infoRaw": {
      "en-US": "<b><keyword=veteran>Veteran</keyword></b> 1.\nWhenever a Unit is <keyword=discard>Discarded</keyword> to your Graveyard, <keyword=boost>Boost</keyword> self by 1 while in your Hand, Deck or on your side of the Board.",
    },
    "keywords": [
      "veteran",
      "discard",
      "boost"
    ],
    "name": {
      "en-US": "Clan Dimun Pirate Captain",
    },
    ...
  },
```

2017-08-10 14:36 UTC, Zolmeister commented on master_xml.py
> +        result = re.findall(r'.*?\<keyword=(.*?)\>.*?', card['infoRaw']['en-US'])
not an issue, but the regex could be cleaner (no `.*?` or unnecessary escape `\<`)
```js
/<keyword=([^>]+)>/
```

2017-08-10 14:37 UTC, Zolmeister commented
rebase, then g2g

2017-08-10 14:38 UTC, Zolmeister approved these changes

2017-08-10 14:47 UTC, jamieadkins95 commented on master_xml.py
> +        result = re.findall(r'.*?\<keyword=(.*?)\>.*?', card['infoRaw']['en-US'])
Fixed.

2017-08-11 03:45 UTC, Tri125 requested changes
Rebase on top of master, force push back to the Feature/keywords branch and it's good to go.

2017-08-11 06:54 UTC, jamieadkins95 commented
I'm honestly not a fan of rebasing. I'd prefer traceability of old branches over having a neat master branch.

Squashing will keep the master branch tidy, and I'd like to leave this branch as it is for full traceability, even if it is messy.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-11 12:53 UTC, Tri125 commented
Alright, no problem.

2017-08-11 12:53 UTC, Tri125 approved these changes

2017-08-11 12:58 UTC, merged